CC=gcc
BIN=passe-partout
OBJS=dbg.o $(BIN).o
CFLAGS+=-I/home/eiselekd/openssl-bin/include 
LDFLAGS=-lcrypto -lssl -L/home/eiselekd/openssl-bin/lib -ldl

all: $(LIB) $(BIN)

$(BIN): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LDFLAGS) 

%.o: %.c
	$(CC) $(CFLAGS) -Wall -g -o $@ -c $<

clean: 
	rm -f $(OBJS) $(BIN)

